### ISSUE TITLE
Excessive logging of `hookImplementationsMap[hook]: invalid key or value`

### ISSUE THREAD

**Issue by richardgaunt** [newrelic/newrelic-php-agent#1099]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

This started with the upgrade to `11.10.0.24`  for new relic php agent

We are getting many, many (1000s) of logs during deployment:

`hookImplementationsMap[hook]: invalid key or value`

This log was implemented as part of: https://github.com/newrelic/newrelic-php-agent/pull/1030

I have run a check within my code base validating the `hookImplementationsMap` (in `ModuleHandler`) but cannot see any issue with the `ModuleHandler::hookImplementationsMap`

See below (I may have got something wrong as the c code is not easily readable for a php developer - please let me know and I can reimplement in my code base):
```  
protected function isValidImplementation() {
    foreach ($this->hookImplementationsMap as $hook_key => $hook_value) {
      // Remimplementing
      //      if (NULL == key || 0 == ZEND_STRING_LEN(key)
      //        || 0 == nr_php_is_zval_valid_array(val)
      //        || 0 == zend_hash_num_elements(Z_ARRVAL_P(val))) {
      //        return true;
      //      } else {
      //        return false;
      //      }

      if ($hook_key === NULL || $hook_value === '' || !is_array($hook_value) || count($hook_value) === 0) {
        return $hook_key;
      }
    }
  }
```

## Steps to Reproduce
Deploy the server with the new relic 

## Expected Behavior

Should not be getting these logs.

## Relevant Logs / Console output

`warning: hookImplementationsMap[hook]: invalid key or value`

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

We are utilising this image (note the new relic download and installation):

https://github.com/uselagoon/lagoon-images/blame/main/images/php-fpm/8.3.Dockerfile

**Comment by richardgaunt** [comment]
Might be good for the new relic agent to specify which entry it found to be invalid

**Comment by richardgaunt** [comment]
I can confirm that blackfire is installed but not activated on our setup

**Comment by zsistla** [comment]
Thank you for your feedback.  This issue has been addressed in the latest New Relic PHP Agent Release [12.0.0.25](https://github.com/newrelic/newrelic-php-agent/releases/tag/v12.0.0.25).  Logging has been modified to reduce the number of logs and to provide more information on the error condition.

**Comment by seanhamlin** [comment]
Just noting that this issue I do not consider resolved. We updated to `12.0.0.25` and still see loads of 

```
2025-08-26 14:00:14.888 +0000 (95 95) warning: hookImplementationsMap[hook]: invalid key
```

Editing `/usr/local/etc/php/conf.d/newrelic.ini` to set 

```
newrelic.loglevel = "error"
newrelic.daemon.loglevel = "error"
```

Stopped the warning spam we were receiving.

**Comment by richardgaunt** [comment]
The logging is saying one of the keys is `NULL` or invalid string.

I patched drupal and created validation of this variable in the `ModulHandler` class to test this variable directly and there is nothing wrong with the variable.

This logging appears to happen on cache rebuild (`drush cr`) and on cron when I assume the container is rebuilt but even when I validated this variable at those times there were no errors.

**Comment by bduranleau-nr** [comment]
I attempted to reproduce this warning with a Drupal 11.0 site on PHP 8.3 and the 12.0.0.25 version of the PHP Agent. I ran `drush cr` in the middle of the application serving requests and was unable to generate any of the `warning` log messages you're seeing. I also verified that the instrumentation is properly detecting and instrumenting the hooks as expected.

At this point, we're going to need more information from your environment to debug the issue, since we are not able to reproduce the problem locally. If you already have a support representative/contract in New Relic, please reach out to them to file a GTSE ticket where we can gather more sensitive information like logs, ini values, and other relevant information.

If you do not have a support contact, you can make a post in our [support forums](https://support.newrelic.com/s/), where a member of our tech support team can reach out to you securely via email to create the internal ticket and gather the pertinent data. I have already contacted the support team directly and let them know that you may be reporting this in the forums and to fast track the ticket creation (please be sure to please reference this github issue in your post).
