### ISSUE TITLE
Large performance regression in 10.3.0

### ISSUE THREAD

**Issue by pgibson1-godaddy** [newrelic/newrelic-php-agent#577]
## Description

We are seeing a very large hit to performance everywhere we are running New Relic after we updated the extension to `10.3.0.315`. It seems like [other users are also seeing this issue](https://discuss.newrelic.com/t/php-new-relic-agent-consumes-all-available-cpu-usage/190886).

Simply switching between `10.2.0.314` and `10.3.0.315` causes some pages for us to be at least an order of magnitude slower (I say at least because the difference is a page taking 6 seconds to load vs. hitting the 60 second timeout we had).

We assumed the performance hit came from the new logging changes so we tried the following different config options, but so far we have not had any success in mitigating the issue:

```
newrelic.cross_application_tracer.enabled = false
newrelic.distributed_tracing_enabled = false
newrelic.span_events_enabled = false
newrelic.application_logging.enabled = false
newrelic.application_logging.forwarding.enabled = false
newrelic.application_logging.metrics.enabled = false
```

Here are some graphs from a couple of different sites on different hardware configurations and you can clearly see when the extension was updated and then reverted:

![2022-11-04 09_55_54](https://user-images.githubusercontent.com/97112726/199946260-59264244-455f-49f3-a9d8-ebd0b6b675ac.png)

![2022-11-04 09_57_23](https://user-images.githubusercontent.com/97112726/199946267-e4c211a7-2237-4de4-9b49-6bb8e14efecb.png)

## Steps to Reproduce

Install `10.3.0.315` extension version with some organic traffic.

## Expected Behavior

No performance degradation.

## Relevant Logs / Console output

N/A

## Your Environment

All environments were Debian Linux with different PHP versions affected (`7.4.32` and `8.0.25` at least).

## Additional context

Reinstalling the older NR extension with no other changes to the environment immediately rectified the issue.

**Comment by ZNeumann** [comment]
Hello @pgibson1-godaddy , thanks for filing this issue! To collect a little more context, could you please add the framework you are using and any additional php packages/libraries?

**Comment by pgibson1-godaddy** [comment]
@ZNeumann These are WordPress sites, and the extensions they are running vary, however both examples here are not really actually using much beyond the relatively standard stuff for WordPress (curl, mysqli, date, etc.) plus also Redis. Here is the extension list from one of the sites in question:

```[PHP Modules]
bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
newrelic
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
pspell
readline
redis
Reflection
relay
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
uuid
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by bduranleau-nr** [comment]
Thanks again for bringing this to the team's attention @pgibson1-godaddy - we believe we've identified the issue, and we are currently working on implementing a fix that should resolve it. We also believe that impact is limited to Wordpress applications, and other frameworks should not see this kind of performance degradation.

In the meantime, downgrading to version `10.2.0.314` should resolve the negative performance impact while we work on putting together a release to formally address it.

**Comment by misiekn** [comment]
Hello @pgibson1-godaddy. To collect a little more context, could you please share additional php packages/libraries (not php modules) and number of WordPress plugins and themes the sites are using?

**Comment by pgibson1-godaddy** [comment]
@misiekn There are a number of different WP sites that were affected and there is seemingly not that much in common between them.

The sites are running a mix of mainstream plugins like WooCommerce, WordPress SEO, Gravity Forms, custom stuff, etc. Some sites are running mostly custom plugins and were still affected.

We were wondering if the problem could come from the additional per-function overhead of [these changes](https://github.com/newrelic/newrelic-php-agent/pull/568/files#diff-9408f6b45682dc2cebef6e4beccd6aae78d1f1c542c82fafdb333a7d8fc83262R406) which could seemingly cause an issue as things balloon.

The sites were running anywhere from 20 - 100 plugins. Most of the time reported during the transactions within the NR interface itself seemed to be coming from just lots of deep loops, but where everything was just slightly slower than the previous release, but the amount of looping really brought that to the surface - but I could be wrong, it's hard to interpret them as NR just says "PHP took a while here".

**Comment by misiekn** [comment]
Thank you for these additional details @pgibson1-godaddy! As stated by @bduranleau-nr [here](https://github.com/newrelic/newrelic-php-agent/issues/577#issuecomment-1304293969) we are working on implementing a fix. Could you contact New Relic support by following [these steps](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket). This way we will be able to gather additional details about your WP applications that are needed to thoroughly test the solution.

**Comment by vdloo** [comment]
hi @bduranleau-nr, we at hypernode (ecommerce hosting) have been monitoring this thread and [this discussion thread](https://discuss.newrelic.com/t/php-new-relic-agent-consumes-all-available-cpu-usage/190886/4) following several messages from concerned users of our platform over the past couple of days and I just wanted to put in our 2 cents and mention that if there's any way for you guys to prioritize addressing this issue with a new version of the new relic extension as soon as possible that would be great. I think we have a pretty good representative sample size of webshops and we have had significant trouble with woocommerce / wordpress based shops that belong to people who are newrelic customers and especially this close to black friday that's really something that's affecting people's trust in new relic as a product. To the extent that we see this having caused issues on our hosting platform I can imagine that there's a lot of users out there in the world who are running into the exact same problem but don't feel the need to report it or haven't been able to pinpoint it back to newrelic. Especially because newrelic is often the tool people rely on for visibility in matters of performance, now that newrelic is actually the issue that is catching people by surprise and that can turn in to a lot of wasted time and frustration.

**Comment by pgibson1-godaddy** [comment]
> Thank you for these additional details @pgibson1-godaddy! As stated by @bduranleau-nr [here](https://github.com/newrelic/newrelic-php-agent/issues/577#issuecomment-1304293969) we are working on implementing a fix. Could you contact New Relic support by following [these steps](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket). This way we will be able to gather additional details about your WP applications that are needed to thoroughly test the solution.

So the New Relic accounts we have access to are not our accounts but our customer owned accounts. It seems like basically every customer we have as an example here is unable to open a support ticket because the plans are free and not paid.

**Comment by beveradb** [comment]
Just adding another voice to flag this as a major issue - a client I'm working with brought me on 10 days ago specifically to help them get to the bottom of a major performance issue with their production sites which began at the start of November.

The issue has impacted customers and lost them revenue, and we've only just now figured out it was caused by New Relic. Thankfully we've resolved it now by uninstalling New Relic, but suffice to say the client isn't happy!

In case it's relevant, the sites are Wordpress multisite with lots of complexity, 60 active plugins, WP-rocket caching and Redis cache, running on EC2 instances provisioned with Elastic Beanstalk.
With caching disabled, page load times for most of the pages on the site is around 4 seconds with NR disabled, or with version `10.2.0.314`. If we install `10.3.0.315` the page load time goes up to around 20 seconds (!) - hence the customer & revenue loss...

**Comment by pgibson1-godaddy** [comment]
> @pgibson1-godaddy Thank you for getting back to us with this information. The other option available to customers with free plans is to use New Relic's community support channel: [Explorers Hub](https://discuss.newrelic.com/). I see you have already reached out [here](https://discuss.newrelic.com/t/php-new-relic-agent-consumes-all-available-cpu-usage/190886/7). You should hear back from one of New Relic's support engineers.

@misiekn thanks - I have responded to the request from support with the available information I have including debug logs with issue reproduction.

**Comment by steven-hoffman-jomashop** [comment]
Note: Similar performance regression from upgrading to 10.x.x noted here: https://github.com/newrelic/newrelic-php-agent/issues/482#issuecomment-1216877039
(From 9.2.x)
(See also: https://discuss.newrelic.com/t/php-agent-performance-regression-in-10-0-0-312-9-20-0-310-did-not-exibit-slowdown/189023)

**Comment by danieliser** [comment]
Saw this over the past week as well. Except our WP site pages went from 0.5s load times to 15-30s load times if they would finish at all.

Troubleshot all kinds of potential plugin issues to track down the performance issue. Was using NR to find it, only to realize NR was the entire cause.

With all plugins active and NR off, back to <1s load times across the board.

**Comment by stewarty** [comment]
Just adding a +1 that we've experienced the same issue.

Almost exact same issue as @beveradb. New (to us) eCommerce client migrated onto hosting. New Relic version bump as part of a deploy, massive unexplained performance degradation.

Disabling the extension resulted in immediate improvement

**Comment by jburianek** [comment]
+1 we're seeing this performance degradation as well.

**Comment by jyrkih** [comment]
+1 same issue for a busy site.

**Comment by Ak-x** [comment]
Thank you for your feedback. We are actively working on a solution.
In the interim we recommend:

- Downgrade the agent to version `10.2.314`
- If the issue is WordPress related; you can stay on `10.3.0.315` but disable WordPress hooks auto-instrumentation by adding this line to newrelic.ini:
  - `newrelic.framework.wordpress.hooks = false`

We additionally are planning a closed beta program to improve future releases of our agent. If you are interested we suggest filing a ticket by following the steps [here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket), where we can engage our General Tech Support engineers.

If you do not have access to this support flow & the ability to open a support ticket directly, we can reach out via a post on the NR [Community Forums](https://discuss.newrelic.com/).

**Comment by tmobilon** [comment]
+1 having the same issue with v. `10.4.0.316`.

Nginx + WordPress + Redis. Tracer is disabled.

**Comment by nlitterat** [comment]
We are experiencing a significant degradation in performance after upgrading to PHP 8 and the newest agent. 
We can not use JIT, which is hurting us from a performance point of view.
We do not use WordPress. We Use Laravel. 
Our solution was to revert to an old version - 9.18.
We saw a 10 -20 % performance gain after that !!!!!
And this is before using JIT.
That is crazy. 
This is a workaround as we want to be on the latest.
Does anyone know if Newrelic acknowledges the issue? What timeline to solve this?

**Comment by misiekn** [comment]
Fixed in [10.5.0 release](https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.5.0.317).

**Comment by nlitterat** [comment]
Hi, I am sorry to say that we still see a large performance degradation using the newest agent 10.5.
Before our testing server, we have response time of 167 ms
after 291.
What can be done?

**Comment by pgibson1-godaddy** [comment]
We're not seeing the original reported issue any more, at least on PHP 8.0, admittedly I didn't test on other versions:
![2023-01-26 14_15_36](https://user-images.githubusercontent.com/97112726/214859182-cccd763f-bb47-4069-8896-d01231162263.png)

**Comment by misiekn** [comment]
Hi @nlitterat! Thank you for bringing this to the team's attention. Could you contact New Relic support by following [these steps](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/#file-ticket). This way we will be able to gather additional details about your application.
